---
title: "Word Embeddings Visual"
author: "Reid McIlroy-Young"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---
<style>                     
.navbar {
  background-color:maroon;
  border-color:black;
}
.navbar-brand {
color:white!important;
}
</style>   
```{r global, include=FALSE}
options(shiny.sanitize.errors = FALSE)
library(ggplot2)
library(plotly)
library(plyr)
library(xkcdcolors)
library(flexdashboard)
library(shinyWidgets)

if (dir.exists('data/')) {
  filesDir <- 'data/'
} else {
  filesDir <- '/home/reid/int-reidmcy/data/'
}


target_names <- c('Economics', 'Stack Overflow', 'Psychology & Neuroscience', 'Combined')
names(target_names) <- c('Economics', 'Computer Science', 'Psychology & Neuroscience', 'Combined')

choices_names <- c('Points', 'Text', '3D')
names(choices_names) <- c('Points', 'Text', '3D')

files <- c('tsne_Economics.csv', 'tsne_Stack Overflow.csv', 'tsne_Psychology & Neuroscience.csv', 'tsne_combined.csv')
colours <- c(name2color("light orange"), name2color("light blue"), name2color("light green"), name2color("black"))

df_attributes <- data.frame(file=files, colour=colours, row.names=target_names)
#row.names(df_attributes) <- names

```

Column {.sidebar}
-----------------------------------------------------------------------

### Introduction

On the right is a plot showing t-SNE embedding of 100-500 words (depending on the options selected) in a 200 dimensional word2vec space (PCA was used to go from 200 to 50). The words are from the tags on three websites: stackoverflow.com, economics.stackexchange.com and psychology.stackexchange.com, while the embedding is trained on abstracts and title of 1.5 million social science papers. The goal of this application is to let you explore the word2vec space and see how different words and contexts affect it. To do this there are three different ways of visualizing it and the datasets can either be combined or viewed separately.


```{r}
pickerInput(inputId = 'var',
            label = 'Dataset',
            choices = target_names,
            selected ='Combined')

pickerInput(inputId = 'choice',
            label = 'Display Type',
            choices = choices_names,
            selected ='Points')

```

### Dataset Discussion

```{r}

renderText({
  if (input$var == 'Combined') {
    out <- "These are the combined set of tags from all three datasets with one t-SNE embedding. You can see in the 2D plots how how separable they are. In the 3D it is much less obvious, mostly due to the limitations of 3D. It seems that computer science words are more isolated than the other two, but not by a large margin. Despite the dataset tripling in size there still are some outliers, interestingly they are not the same as the outliers with one dataset. There are a couple of words that are shared between the vocabularies so they are displayed twice."
  } else if (input$var == 'Economics') {
  out <- "This is the tags from economics.stackexchange.com. The power of the t-SNE embedding is evident as there are clusters, e.g. one seem to focus on probability/risk (just right of the center) while another on optimization/programming (lower left side), but there is also a central ball around money/trade showing the homogeneity of the word usage. In 3D there are a few interesting outliers, namely 'bitcoin' (near the camera) and 'political-economy' (up high).
"
  } else if (input$var == 'Psychology & Neuroscience') {
  out <- "These are the tags from psychology.stackexchange.com It is similar to economics with a central blob, although there does seem to be bias towards computational words, likely due to the community being small and on a very technical site. The collection of chemicals in the upper right shows that they are being treated differently than the other words, which meets expectations. In 3D a few outliers can be found 'Jung' is the most interesting ads it shows a major problem in word embedding, homonyms, Jung is the name of many people and they get referenced in many places, not just where Carl might be."
  } else if (input$var == 'Stack Overflow') {
  out <- "These are the tags from stackoverflow.com They had be filtered as the pool was much larger than the others. There is an interesting bimodal effect in the 2D plots, most visible in the points plot. It is somewhat unclear what causes the two clusters, although one seems to be more front end and the other back end. In 3D there is one main extreme, 'tabs' which is likely do to many people talking about tagging/tags in many contexts outside of computer science."
    }
  out
})
```


### Display Discussion

```{r}

renderText({
  if (input$choice == '3D') {
    out <- "The 3D plot was very challenging to get running, and the customization options were either lacking or broken, thus the axis are still ugly and the legend festers in the corner. The plot is very useful though as by adding another dimension the embedding changes significantly, the spherical nature of the results is still very evident, but outliers start appearing which is quite interesting and visually intriguing. I tried getting a 3D version of the text running but every piece of text would have had to been placed individually in a big for loop and it was too slow and unreliable "
  } else if (input$choice == 'Text') {
  out <- "These are the closest plots to those in my thesis, although I was not able to get alpha scaling to work. The words do tend to overlap, but zooming in will solve that and besides very aggressive alpha or size scaling it's hard to fix. The words are scaled by the rank on stackexchange with the processing all being done by a Python script before R is even launched. The colours are also handled this way to give consistency across the different visuals."
  } else if (input$choice == 'Points') {
  out <- "The points provide the clearest view of the data, at the cost of showing little else, you don't get the ease of cluster interpretation that text gives you or the outliers that 3D does, but the hover text helps (it was annoying to setup). "
  }
  out
})
```


### Conclusion

This web app lets people interact with an word embedding in a more visual way then the normal comparison task. By letting the user pan and zoom though the space people can find their own small insights without being beholden to the original author. It also hopefully gives insights into the folly of low dimensional embedding of high dimensionless data, with the major differences between 2 and 3 dimensions. The text and point plots show slightly different views, giving limited node specific information and density information respectively.

Column 
-----------------------------------------------------------------------

### t-SNE embeding of Word2Vec space
```{r}

df_target <- reactive({
  if (input$choice == '3D' ||input$choice ==  'Table 3D') {
    df <- read.csv(paste(filesDir, 'tsne_', input$var, '_3d.csv', sep = ''))
  } else {
    df <- read.csv(paste(filesDir, 'tsne_', input$var, '.csv', sep = ''))
  }
})


renderPlotly({
  if (input$choice == '3D') {
    ax <- list(title = "")
    p <- plot_ly(df_target(), x=~tsne_0, y=~tsne_1, z=~tsne_2, color = ~colour_class, size = ~size_objs * 5,
                hoverinfo = 'text', type='scatter3d',
                text = ~paste('Tag: ', tag,
                  '\nSource: ', cName,
                  '\n Count: ', count,
                  '\n Rank: ', rank))
    p<- add_markers(p)
    p <- layout(p, showlegend = FALSE, scene = list(xaxis=ax,yaxis=ax,zaxis=ax))
    p
  } else {
    colour_val <- df_target()$colour_class
    tsne_plot <- ggplot(data = df_target(), aes(x=tsne_0, y=tsne_1, label=tag, size = size_objs, fill=cName, 
                                                 text = paste('Tag: ', tag,
                                                              '\nSource: ', cName,
                                                              '\n Count: ', count,
                                                              '\n Rank: ', rank)))
  if (input$choice == 'Text') {
    tsne_plot <- tsne_plot + 
      geom_text(colour=colour_val)
  } else {
    tsne_plot <- tsne_plot +
      geom_point(colour=colour_val, fill=colour_val, pch=1)
  }
  tsne_plot <- tsne_plot +
    labs(title = input$var) +
    theme(plot.title = element_text(size =12),
        axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        legend.position="none")
  ggplotly(tsne_plot, tooltip = c("text"))
  } 
})

```
